/*
1. Drive the target virtual page number to MMU to trigger TLB lookup and miss
2. After TLB miss, it will send a request to PTW and wait for the response. 
3. Acting as main memory, drive the PTE (mock page table walking) to PTW after a few cycles. (both Sv32's L1 and L0 PTE)
4. The PTW will then fill the TLB entry, so the CPU can retry the request and get the physical tag in the next cycle. (monitor physical_tag_valid_out and physical_tag_out)
*/

#include <iostream>
#include <memory>
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VMMU.h" // The header generated by Verilator


vluint64_t main_time = 0; // Global simulation time


// Simualted CPU responsible for driving MMU's inputs and receiving outputs 
class SimulatedEngine {
private:
    VMMU* dut;
    const int PTW_RESPONSE_LATENCY = 10; // Number of cycles after which PTW response will be ready
    int ptw_response_counter = 0;
    int mocked_pte_data = 0x3555504F; // Mocked PTE data to be returned to PTW (set last hex digit to F for valid, E for invalid to trigger page fault)
    int test_types = 0;
    bool request_pending = false; // Flag to indicate if we are currently counting down for a request
public:
    SimulatedEngine(VMMU* dut_ptr): dut(dut_ptr), ptw_response_counter(0), mocked_pte_data(0x3555504F), test_types(0), request_pending(false) {}
    
    // CPU interface - drive vpn to MMU to trigger TLB lookup and miss
    void CPU_drive_vpn(int vaddr, int req_type = 1, int test_type = 0) { // req_type: 1 for load, 0 for store
        dut->Virtual_Address_in = vaddr;
        dut->load_req_in = req_type; // or dut->store_req_in = 1 for write request
        dut->store_req_in = !req_type;
        test_types = test_type;

        if(test_types == 0) { // Initial TLB Miss Handling Test
            mocked_pte_data = 0x3555500F; 
        }
        else if(test_types == 1) { // Page Fault Test
            mocked_pte_data = 0x1234500F; 
        } 
        else if(test_types == 2) { // Svadu: Access bit Management Test
            mocked_pte_data = 0x5644400F; // The root PTE access bit should be 0
        }
    }
    // CPU interface - catch the physical tag output from MMU and print it out
    // observe physical_tag_out, physical_tag_valid_out, Physical_Page_ID_Miss_out, page_fault_out,
    void monitor_mmu_output() {
        if(dut->Physical_Page_ID_Miss_out){
            std::cout << "TLB Miss detected!" << std::endl;
        }
        if(dut->physical_tag_valid_out && test_types == 0) {
            std::cout << "Test 1 Completed - Received Physical Tag: 0x" << std::hex << dut->physical_tag_out << std::dec << std::endl;
            dut->load_req_in = 0;  // Deasserted after CPU sees Physical_Page_ID_valid_out
            dut->store_req_in = 0;
            dut->Virtual_Address_in = 0;
        }
        if(dut->ptw_busy_out && !request_pending && !dut->page_fault_out) {
            std::cout << "PTW is busy walking the page table..." << std::endl;
        }
        if(dut->page_fault_out && test_types == 1) {
            std::cout << "Test 3 Completed - Page Fault detected!" << std::endl;
        }

        if(dut->ptw_mem_req_valid_out && dut->ptw_mem_req_type_out && test_types == 2) {
            std::cout << "Received Updated PTE: 0x" << std::hex << dut->ptw_mem_write_data_out << std::dec << std::endl;
            std::cout << "Test 2 Completed" << std::endl;
        }
    }

    void ptw_response_handler() {
        dut->ptw_mem_data_valid_in = 0; // Default state: deassert data valid

        if(dut->ptw_mem_req_valid_out && !request_pending) {
            std::cout << "Received PTW Memory Request! Starting countdown for response..." << std::endl;
            ptw_response_counter = PTW_RESPONSE_LATENCY;
            request_pending = true;
        }
        
        if(request_pending) {
            if (ptw_response_counter > 0) {
                ptw_response_counter--;
            }
            else{
                std::cout << "Providing Mocked PTE data to PTW: 0x" << std::hex << mocked_pte_data << std::dec << std::endl;
                dut->ptw_mem_read_data_in = mocked_pte_data; 
                dut->ptw_mem_data_valid_in = 1;

                if(test_types == 0){
                    mocked_pte_data += 0x0AAAA040; // Change the mocked PTE data for the next response to simulate different PTEs for L1 and L0 walk
                }
                else if(test_types == 1) {
                    mocked_pte_data = 0x2222204E; // Set the access bit to 1 and the valid bit of the mocked PTE data to 0 to trigger a page fault (invalidate leaf PTE) 
                } 
                else if(test_types == 2) {
                    mocked_pte_data = 0x7654320F; // Set the access bit to 0 to trigger Svadu handling 
                }
                request_pending = false;
            }
        }
    }
};

void tick_clock(VMMU* dut, VerilatedVcdC* tfp, SimulatedEngine& engine) {
    dut->clk = 0;
    dut->eval();
    tfp->dump(main_time++); // timestamp of current cycle's falling edge (for dumps)
    
    dut->clk = 1;
    dut->eval();
    engine.monitor_mmu_output();
    engine.ptw_response_handler();
    tfp->dump(main_time++); // timestamp of current cycle's rising edge
}

int main(int argc, char** argv) {
    // 1. Setup Engine
    Verilated::commandArgs(argc, argv); 
    Verilated::traceEverOn(true);       

    // 2. Instantiate DUT and Tracer
    VMMU* dut = new VMMU;       
    VerilatedVcdC* tfp = new VerilatedVcdC; 
    SimulatedEngine engine(dut);
    
    dut->trace(tfp, 99);                
    tfp->open("waveform_mmu.vcd");          

    // 3. The Simulation Loop
    dut->rst_n = 0;
    dut->flush = 0;

    for(int i=0; i<5; i++) tick_clock(dut, tfp, engine); // Hold reset for 5 cycles
    dut->rst_n = 1;
    std::cout << "Reset lifted." << std::endl;

    // Set SATP to point to the root page table frame (for Sv32, the root PTE frame number is the lower bits 22 of SATP
    // The first bit is MODE bit indicating Sv32, the rest bits are ASID which is not used in this test)
    dut->satp_in = 0x8000ABCD; // set the base address of root page table frame to the lower 20 bits of satp CSR with [21:20] hardwired to 0.
    
    std::cout << "TLB Miss Handling Test (Test 1) Started..." << std::endl;
    // TLB Miss test
    engine.CPU_drive_vpn(0xDEADBEEF, 1, 0); // Drive the virtual (address) page number to trigger TLB lookup and miss
    for(int i=0; i<40; i++) { // Run the simulation for enough cycles to see the entire TLB miss handling process
        tick_clock(dut, tfp, engine);
    }

    std::cout << "Svadu Handling Test (Test 2) Started..." << std::endl;
    // Access bit Management - On TLB Miss, assuming the requested page has its access bit de-asserted
    engine.CPU_drive_vpn(0x77777777, 1, 2); // Drive the virtual (address) page number to trigger TLB lookup and miss
        for(int i=0; i<25; i++) { // Run the simulation for enough cycles to see the entire TLB miss handling process
        tick_clock(dut, tfp, engine);
    }

    std::cout << "Page Fault Test (Test 3) Started..." << std::endl;
    // TLB Miss with Page Fault test
    engine.CPU_drive_vpn(0x12345678, 1, 1); // Drive the virtual (address) page number to trigger TLB lookup and miss
    for(int i=0; i<25; i++) { // Run the simulation for enough cycles
        tick_clock(dut, tfp, engine);
    }

    std::cout << "Simulation Completed" << std::endl;

    // 4. Cleanup
    dut->final();
    tfp->close();
    delete dut;
    delete tfp;
    return 0;
}