#include <iostream>
#include <memory>
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VL1Cache.h" // The header generated by Verilator

vluint64_t main_time = 0; // Global simulation time


class SimulatedMemory {
private:
    VL1Cache* dut;
    int delay_counter;
    bool request_pending;
    uint32_t latched_block_id;
    
    // Configurable latency
    const int MEMORY_LATENCY = 15; 

public:
    SimulatedMemory(VL1Cache* dut_ptr) : dut(dut_ptr), delay_counter(0), request_pending(false), latched_block_id(0) {}

    // Receive block request and handle block return
    // Assuming no L2 MSHR so this class can only handle one block request from L1 at a time.
    void block_request_handler() {
        // Default state: drop valid signal after 1 cycle
        dut->L2_return_block_valid_in = 0;

        // Check for incoming requests from L1 Cache, and if there is not a pending one, accept it and start latency countdown
        if (dut->L2_block_req_out == 1 && !request_pending) {
            std::cout << "[Memory] Received Request for Block ID: 0x" << std::hex << dut->L2_req_block_id_out << std::dec << " at time " << main_time << std::endl;
            request_pending = true;
            delay_counter = MEMORY_LATENCY;
            latched_block_id = dut->L2_req_block_id_out;
        }

        // count down until zero and return data
        if (request_pending) {
            if (delay_counter > 0) {
                delay_counter--;
            } 
            else { // counter hits 0
                std::cout << "[Memory] Returning Block ID: 0x" << std::hex << latched_block_id << std::dec << " at time " << main_time << std::endl;
                
                dut->L2_return_block_valid_in = 1;
                dut->L2_return_block_id_in = latched_block_id;
                
                // Mock some data: Fill the 64-byte line with a repeating pattern
                for(int i = 0; i < 16; i++) {
                    dut->L2_return_block_data_in[i] = (uint32_t)(0xDEADBEEF + i); // Setting 32-bit chunks of the 512-bit wide bus
                }
                
                request_pending = false; // Request fulfilled
            }
        }
    }
};

int main(int argc, char** argv) {
    // Initialize Verilator
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    // Instantiate the DUT and the Trace Dumper
    VL1Cache* dut = new VL1Cache; // Create a pointer to the transpiled L1Cache module
    VerilatedVcdC* tfp = new VerilatedVcdC;
    
    dut->trace(tfp, 99); // Trace 99 levels of hierarchy
    tfp->open("waveform_l1cache.vcd");

    // Instantiate our modular memory model
    SimulatedMemory l2_memory(dut);

    // Helper lambda to tick the clock
    auto tick_clock = [&]() {
        dut->clk = 0;
        dut->eval();
        tfp->dump(main_time++); // timestamp of current cycle's falling edge (for dumps)
        
        dut->clk = 1;
        dut->eval();
        l2_memory.block_request_handler(); // Evaluate memory on rising edge
        tfp->dump(main_time++); // timestamp of current cycle's rising edge
    };

    // --- INITIALIZATION & RESET ---
    std::cout << "Starting Simulation..." << std::endl;
    dut->rst_n = 0;
    dut->flush = 0;
    dut->load_req_in = 0;
    dut->store_req_in = 0;
    dut->physical_tag_valid_in = 0;
    
    for(int i=0; i<5; i++) tick_clock(); // Hold reset for 5 cycles
    dut->rst_n = 1;
    std::cout << "Reset lifted." << std::endl;
    dut->satp_in = 0x8000ABCD; // set the Satp CSR so TLB entries can fill in ASID

    // --- TEST 1: Simple Load Miss & MSHR Allocation ---
    tick_clock();
    
    std::cout << "Injecting Load Request (Virtual Index: 0x2, Tag: 0xABC)" << std::endl;
    int v_address = 0xABC2 << 6; // Shift index to offset bit position (there are 4 index bits (16 sets) and 6 offset bits)
    
    for(int i=0; i<4; i++) { // target list size is 4
        tick_clock(); 
        // Cycle 1: Request enters Cache
        // Setup CPU Inputs
        dut->virtual_address_in = v_address+4*i; // Access subsequent words in the same cache line
        dut->load_req_in = 1;
        dut->lsq_tag_in = 0x2 + i; // Set LSQ tags; this will yield a wakeup vector of 0x3c when it returns (bit 2,3,4,5 set)
        tick_clock();
        // Cycle 2: physical tag enters Cache from simulated TLB/MMU
        dut->physical_tag_in = 0xABC; // Accessing same cache line
        dut->physical_tag_valid_in = 1;
        tick_clock();
        // Cycle 3: Deassert request
        dut->load_req_in = 0; // Deassert request after receving physical tag
        dut->physical_tag_valid_in = 0;
    }

    // Run for enough cycles to see the memory return the data and wake up the LSQ
    for(int i=0; i<15; i++) {
        tick_clock();
        
        // Check if LSQ was woken up
        if (dut->lsq_wakeup_vector_out != 0) {
            std::cout << "[CPU] LSQ Wakeup Vector asserted: 0x" << std::hex << (int)dut->lsq_wakeup_vector_out << std::dec << " at time " << main_time << std::endl;
        }
    }

    // --- CLEANUP ---
    std::cout << "Simulation complete." << std::endl;
    
    dut->final();
    tfp->close();
    
    delete dut;
    delete tfp;
    
    return 0;
}