#include <iostream>
#include <memory>
#include <verilated.h>
#include <verilated_vcd_c.h> // vcd (Value Change Dump) file generation library for waveform viewing
#include "VL1Cache.h" // The header generated by Verilator

vluint64_t main_time = 0; // Global simulation time

class SimulatedMemory {
private:
    VL1Cache* dut;
    int delay_counter;
    bool request_pending;
    uint32_t latched_block_id;

    // Configurable latency
    const int MEMORY_LATENCY = 20; // Increased to keep MSHR pending while stores are issued for coalescing
public:
    SimulatedMemory(VL1Cache* dut_ptr): dut(dut_ptr), delay_counter(0), request_pending(false), latched_block_id(0) {}

    // Receive block request and handle block return
    // Assuming no L2 MSHR so this class can only handle one block request from L1 at a time.
    void block_request_handler() {
        // Default state: drop valid signal after 1 cycle
        dut->L2_return_block_valid_in = 0;

        // Check for incoming requests from L1 Cache, and if there is not a pending one, accept it and start latency countdown
        if (dut->L2_block_req_out == 1 && !request_pending) {
            std::cout << "[Memory] Received Request for Block ID: 0x" << std::hex << dut->L2_req_block_id_out << std::dec << " at time " << main_time << std::endl;
            request_pending = true;
            delay_counter = MEMORY_LATENCY;
            latched_block_id = dut->L2_req_block_id_out;
        }

        // count down until zero and return data
        if (request_pending) {
            if (delay_counter > 0) {
                delay_counter--;
            } 
            else { // counter hits 0
                std::cout << "[Memory] Returning Block ID: 0x" << std::hex << latched_block_id << std::dec << " at time " << main_time << std::endl;
                
                dut->L2_return_block_valid_in = 1;
                dut->L2_return_block_id_in = latched_block_id;
                
                // Mock some data: Fill the 64-byte line with a repeating pattern
                for(int i = 0; i < 16; i++) {
                    dut->L2_return_block_data_in[i] = (uint32_t)(0x11111111 + i); // Setting 32-bit chunks of the 512-bit wide bus
                }
                
                request_pending = false; // Request fulfilled
            }
        }
    }

    // Observe L2_evict_block_valid_out, L2_evict_block_id_out, L2_evict_block_data_out 
    void Evicted_block_handler() {
        if(dut->L2_evict_block_valid_out) {
            std::cout << "[Memory] Received Evicted Block ID: 0x" << std::hex << dut->L2_evict_block_id_out << std::dec << " at time " << main_time << std::endl;
            std::cout << "[Memory] Evicted Block Data: ";
            // print the evicted block data (DEADBEEB, DEADBEEC, DEADBEEED, DEADBEEE, DEADBEEF, and the rest should be 0x11111116, 0x11111117, ...)
            for(int i = 0; i < 16; i++) {
                std::cout << std::hex << dut->L2_evict_block_data_out[i] << " ";
            }
            std::cout << std::dec << std::endl;
        }
    }
};


void tick_clock(VL1Cache* dut, VerilatedVcdC* tfp, SimulatedMemory& memory) {
    dut->clk = 0;
    dut->eval(); // negedge evaluation
    tfp->dump(main_time);
    main_time++;

    dut->clk = 1;
    dut->eval(); // posedge evaluation
    memory.block_request_handler(); // Check for block requests and handle them on the rising edge
    memory.Evicted_block_handler();
    tfp->dump(main_time);
    main_time++;
}


int main(int argc, char** argv) {
    // 1. Setup Engine
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    // 2. Instantiate objects: DUT, SimulatedMemory, and Trace Dumper
    VL1Cache* dut = new VL1Cache;    
    SimulatedMemory l2_memory(dut);
    VerilatedVcdC* tfp = new VerilatedVcdC;
    dut->trace(tfp, 99); // Trace 99 levels of hierarchy
    tfp->open("waveform_l1cache.vcd");

    // 3. The Simulated Region
    // --- INITIALIZATION & RESET ---
    std::cout << "Starting Simulation..." << std::endl;
    dut->rst_n = 0;
    dut->flush = 0;
    dut->load_req_in = 0;
    dut->store_req_in = 0;
    dut->physical_tag_valid_in = 0;

    for(int i=0; i<5; i++) tick_clock(dut, tfp, l2_memory);
    dut->rst_n = 1;
    std::cout << "Reset lifted." << std::endl;
    dut->satp_in = 0x8000ABCD; // set the Satp CSR so TLB entries can fill in ASID

    tick_clock(dut, tfp, l2_memory);


    std::cout << "Issuing Store Requests for Coalescing..." << std::endl;
    int v_address = 0xABC2 << 6; // Shift index to offset bit posiion (there are 4 index bits (16 sets) and 6 offset bits)
    // issuing 5 store requests for the same block for store buffer coalescing
    for(int i=0; i<5; i++) { 
        tick_clock(dut, tfp, l2_memory);
        dut->virtual_address_in = v_address + (i * 4); // i * 4 ensures consecutive 32-bit word addresses
        dut->store_req_in = 1;
        dut->store_byte_en_in = 0xF; // writing full 4 bytes
        dut->store_data_in = 0xDEADBEEB + i; // The block's first 5 words should be DEADBEEB, DEADBEEC, DEADBEEED, DEADBEEE, DEADBEEF respectively after coalescing
        tick_clock(dut, tfp, l2_memory);
        dut->physical_tag_valid_in = 1; // Assume TLB translation is ready immediately for this test
        dut->physical_tag_in = 0xABC; // Provide the physical tag corresponding to the virtual address (set equal to virtual tag for simplicity now)
        tick_clock(dut, tfp, l2_memory);
        dut->store_req_in = 0;
        dut->physical_tag_valid_in = 0; 
    }
    // wait for a few cycle to make sure the missing line is returned to L1
    for(int wait=0; wait<20; wait++) {
        tick_clock(dut, tfp, l2_memory); // wait >20 cycles for the load to resolve
    }

    std::cout << "Issuing Load Requests to fill up the set..." << std::endl;
    // load requests to fill the whole set and set up eviction scenario
    for(int i=1; i<4; i++) {
        tick_clock(dut, tfp, l2_memory);
        dut->virtual_address_in = v_address + (i << 10); // increment tag by one to target the same index but different way
        dut->load_req_in = 1;
        tick_clock(dut, tfp, l2_memory);
        dut->physical_tag_valid_in = 1;
        dut->physical_tag_in = 0xABC + i; // Provide the physical tag (same as virtual tag for simplicity)
        tick_clock(dut, tfp, l2_memory);
        dut->load_req_in = 0;
        dut->physical_tag_valid_in = 0;
        // run for a few more cycles
        for(int wait=0; wait<25; wait++) {
            tick_clock(dut, tfp, l2_memory); // wait >20 cycles for the load to resolve
        }
    }

    std::cout << "Triggering Eviction..." << std::endl;
    // Now all 4 ways of the set are occupied, the next load request to the same set should trigger eviction of the dirty line
        tick_clock(dut, tfp, l2_memory);
        dut->virtual_address_in = v_address + (4 << 10); // increment tag by one to target the same index but different way
        dut->load_req_in = 1;
        tick_clock(dut, tfp, l2_memory);
        dut->physical_tag_valid_in = 1;
        dut->physical_tag_in = 0xABC + 4; // tag not present in the cache line
        tick_clock(dut, tfp, l2_memory);
        dut->load_req_in = 0;
        dut->physical_tag_valid_in = 0;
        
    // Polling for the eviction valid signal from L1 for a few cycles and printing the evicted block's info in the SimulatedMemory class.
    // Observe L2_evict_block_valid_out, L2_evict_block_id_out, L2_evict_block_data_out 
    // l2_memory.Evicted_block_handler();
    for(int wait=0; wait<30; wait++) { // Increase wait to give enough time for 20 cycle latency + eviction
        tick_clock(dut, tfp, l2_memory); 
    }

    // 4. Cleanup
    dut->final();
    tfp->close();
    delete dut;
    delete tfp;
    return 0;
}
